version: "3"
services:
  cadewdevemailer:
    image: cadewdevemailer:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 8989
    ports:
      - "8989:8989"

  cadewdevemailnginx:
    image: cadewdevemailernginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
